import streamlit as st

from llm import get_llm
from rag import answer
from retrieval import build_retriever


@st.cache_resource(show_spinner="Loading knowledge base...")
def load_retriever():
    # Built once per server process and saved to .index/, not on every rerun.
    return build_retriever()


retriever = load_retriever()
configured = get_llm()
llm_name, llm = configured if configured else ("none", None)

st.title("SJSU King Library Chatbot")
if llm is None:
    st.caption("No LLM configured: answers are quoted from the knowledge base.")
else:
    st.caption(f"Answers generated by {llm_name} from retrieved knowledge-base chunks "
               f"(retrieval: {retriever.mode}).")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

st.subheader("Ask me about SJSU Library services, staff, or forms")
user_input = st.text_input("You:")

if user_input:
    try:
        result = answer(user_input, retriever, llm)
    except Exception as err:  # network / API errors: still answer from the knowledge base
        st.warning(f"The LLM call failed ({err}); quoting the knowledge base instead.")
        result = answer(user_input, retriever, None)

    reply = result.text
    if result.mode == "quoted":
        reply = f"*Quoted from the knowledge base:* {reply}"
    if result.sources:
        reply += "\n\n" + "\n".join(f"[{n}] `{src}`" for n, src in result.sources)
    st.session_state.chat_history.append(("You", user_input))
    st.session_state.chat_history.append(("Bot", reply))

for speaker, text in st.session_state.chat_history:
    st.markdown(f"**{speaker}:** {text}")
